=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a2_personaSM.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NIF" type="xs:string"/>
        <xs:element name="nom" type="xs:string"/>
        <xs:element ref="cognoms" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="telefons" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="genero" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="cognoms">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cognom" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="telefons">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="telefon" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a2_personaSM.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="a2_personaSM.xsd"
         genero="masculino">
    <NIF>12345678A</NIF>
    <nom>Eddard</nom>
    <cognoms>
        <cognom>Stark</cognom>
        <cognom></cognom>
    </cognoms>
    <telefons>
        <telefon>123456789</telefon>
        <telefon>987654321</telefon>
    </telefons>
</persona>
