=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a4_classeSM.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="classe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumne" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NIF" type="xs:string" minOccurs="1"/>
              <xs:element name="nom" type="xs:string" minOccurs="1"/>
              <xs:element name="cognoms" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cognom" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a4_classeSM.xml
<?xml version="1.0" encoding="UTF-8"?>
<classe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="a4_classeSM.xsd">
    <alumne>
        <NIF>12345678A</NIF>
        <nom>Daenerys</nom>
        <cognoms>
            <cognom>Targaryen</cognom>
            <cognom></cognom>
        </cognoms>
    </alumne>
    <alumne>
        <NIF>98765432B</NIF>
        <nom>Tyrion</nom>
        <cognoms>
            <cognom>Lannister</cognom>
        </cognoms>
    </alumne>
    <alumne>
        <NIF>45678901C</NIF>
        <nom>Arya</nom>
        <cognoms>
            <cognom>Stark</cognom>
            <cognom></cognom>
            <cognom></cognom>
        </cognoms>
    </alumne>
    <alumne>
        <NIF>23456789D</NIF>
        <nom>Jon</nom>
        <cognoms>
            <cognom>Snow</cognom>
        </cognoms>
    </alumne>
    <alumne>
        <NIF>34567890E</NIF>
        <nom>Sansa</nom>
        <cognoms>
            <cognom>Stark</cognom>
            <cognom></cognom>
        </cognoms>
    </alumne>
</classe>
