=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a5_classeSM.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="classe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tutor" type="personaType"/>
        <xs:element name="alumnes" type="alumnesType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="personaType">
    <xs:sequence>
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="cognoms" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="cognom" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="telefons" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="telefon" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="correus" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="correu" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="NIF" type="xs:string" use="required"/>
    <xs:attribute name="genero" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="alumnesType">
    <xs:sequence>
      <xs:element name="alumne" type="personaType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a5_classeSM.xml
<?xml version="1.0" encoding="UTF-8"?>
<classe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="a5_classeSM.xsd">
 <tutor NIF="123456789A">
        <nom>Juan</nom>
        <cognoms>
            <cognom>Gomez</cognom>
            <cognom>Perez</cognom>
        </cognoms>
        <telefons>
            <telefon>123456789</telefon>
            <telefon>987654321</telefon>
        </telefons>
        <correus>
            <correu>juan@juan.com</correu>
            <correu>juan@gmail.com</correu>
        </correus>
    </tutor>
    <alumnes>
        <alumne NIF="987654321B">
            <nom>Maria</nom>
            <cognoms>
                <cognom>Lopez</cognom>
                <cognom>Martinez</cognom>
            </cognoms>
            <telefons>
                <telefon>111222333</telefon>
            </telefons>
            <correus>
                <correu>maria@example.com</correu>
                 <correu>maria@maria.com</correu>
            </correus>
        </alumne>
        <alumne NIF="123456678K">
            <nom>Paca</nom>
            <cognoms>
                <cognom>paquita</cognom>
                <cognom>Martinez</cognom>
            </cognoms>
            <telefons>
                <telefon>111222333</telefon>
            </telefons>
            <correus>
                <correu>paca@example.com</correu>
            </correus>
        </alumne>
        <alumne NIF="6456464354P">
            <nom>Maria</nom>
            <cognoms>
                <cognom>Lopez</cognom>
                <cognom>Martinez</cognom>
            </cognoms>
            <telefons>
                <telefon>111222333</telefon>
            </telefons>
            <correus>
                <correu>maria@example.com</correu>
            </correus>
        </alumne>
        <alumne NIF="123456789P">
            <nom>jose</nom>
            <cognoms>
                <cognom>Lopez</cognom>
                <cognom>Martinez</cognom>
            </cognoms>
            <telefons>
                <telefon>111222333</telefon>
            </telefons>
            <correus>
                <correu>jose@example.com</correu>
            </correus>
        </alumne>
    </alumnes>
</classe>
