=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a6_coopSM.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cooperativa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="soci" type="sociType" minOccurs="6" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="sociType">
        <xs:sequence>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="numero" type="xs:integer" />
                    <xs:element name="dataAlta" type="xs:date" />
                </xs:sequence>
                <xs:sequence>
                    <xs:element name="clauAlfanumerica" type="xs:string" />
                </xs:sequence>
            </xs:choice>
            <xs:element name="nom" type="xs:string" />
            <xs:element name="cognoms">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="cognom" type="xs:string" minOccurs="1" maxOccurs="2" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="dataNaixement" type="xs:date" minOccurs="0" />
            <xs:element name="edat" type="xs:integer" minOccurs="0" />
            <xs:element name="telefons">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="telefon" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== lsanchez010993/prueba1234/A04_05pi_sanchez_luis/a6_coopSM.xml
<?xml version="1.0" encoding="UTF-8"?>
<cooperativa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="a6_coopSM.xsd">
    <soci>
        <numero>1001</numero>
        <dataAlta>2023-01-15</dataAlta>
        <nom>Amador</nom>
        <cognoms>
            <cognom>Rivas</cognom>
        </cognoms>
        <dataNaixement>1975-08-15</dataNaixement>
        <edat>47</edat>
        <telefons>
            <telefon>111111111</telefon>
            <telefon>222222222</telefon>
        </telefons>
    </soci>
    <soci>
        <numero>1002</numero>
        <dataAlta>2023-02-01</dataAlta>
        <clauAlfanumerica>XYZ789</clauAlfanumerica>
        <nom>Enrique</nom>
        <cognoms>
            <cognom>Pastor</cognom>
        </cognoms>
        <dataNaixement>1960-05-10</dataNaixement>
        <edat>62</edat>
        <telefons>
            <telefon>333333333</telefon>
        </telefons>
    </soci>
    <soci>
        <numero>1003</numero>
        <dataAlta>2023-03-20</dataAlta>
        <clauAlfanumerica>LMN456</clauAlfanumerica>
        <nom>Antonio</nom>
        <cognoms>
            <cognom>Recio</cognom>
        </cognoms>
        <dataNaixement>1968-12-03</dataNaixement>
        <edat>54</edat>
        <telefons>
            <telefon>444444444</telefon>
            <telefon>555555555</telefon>
        </telefons>
    </soci>
    <soci>
        <numero></numero>
        <dataAlta></dataAlta>
        <clauAlfanumerica>XYZ789</clauAlfanumerica>
        <nom>SinNombre</nom>
        <cognoms>
            <cognom>SinApellido</cognom>
            <cognom>SinApellido</cognom>
        </cognoms>
        <dataNaixement></dataNaixement>
        <edat>35</edat>
        <telefons>
            <telefon>987654321</telefon>
            <telefon>123456789</telefon>
        </telefons>
    </soci>
</cooperativa>
